version: "3.9"
services:
  db:
    image: postgres:15.1
    volumes:
      # - ./tmp/db:/var/lib/postgresql/data
      - "postgres:/data/postgres"
    environment:
      POSTGRES_PASSWORD: password
      BUNDLE_FORCE_RUBY_PLATFORM: "true"
      PGDATA: /data/postgres
    ports:
      - "6543:5432"

  mongo:
    image: mongo:4.4.3
    volumes:
      - ./tmp/mongodata:/data/db/data
    ports:
      - "27017:27017"

  redis:
    image: 'redis:7.0.8'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq -C ./config/sidekiq.yaml
    volumes:
      - '.:/scratch'
      - .:/tmp/sidekiq' # don't mount tmp directory
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

  server:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/scratch
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

volumes:
  redis:
  postgres:
