version: "3.9"
services:
  redis:
    image: 'redis:7.0.8'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - 'redis'
    build: .
    command: bundle exec sidekiq -C ./config/sidekiq.yaml
    volumes:
      - '.:/scratch'
      - .:/tmp/sidekiq' # don't mount tmp directory
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

  server:
    build: .
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    volumes:
      - .:/scratch
      - /scratch/node_modules
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
     - redis
     - chrome
    environment:
     - APP_HOST=http://server:4000
     - REDIS_URL_SIDEKIQ=redis://redis:6379/1
     - SELENIUM_HOST=chrome
     - SELENIUM_PORT=4444
    stdin_open: true
    tty: true

  chrome:
    image: selenium/standalone-chrome-debug:3.141.59
    ports:
      - "4444:4444"
      - "5900:5900"
    environment:
      - SELENIUM_HOST=chrome
      - SELENIUM_PORT=4444
      
  mongo:
    image: mongo:4.4.3
    volumes:
      - ./tmp/mongodata:/data/db/data
    ports:
      - "27017:27017"

volumes:
  redis:
  chrome: 
